// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export interface AudioDeviceDTO {
    "id": string;
    "name": string;
    "isDefault": boolean;
}

export interface AudioDevicesDTO {
    "capture": AudioDeviceDTO[] | null;
    "playback": AudioDeviceDTO[] | null;
    "selectedCapture": string;
    "selectedPlayback": string;
}

export interface AudioProfileDTO {
    "codec": string;
    "sampleRate": number;
    "channels": number;
    "frameDurationMs": number;
    "bitrate": number;
    "application": string;
}

export interface AudioStateDTO {
    "muted": boolean;
    "deafened": boolean;
    "rnnoiseEnabled": boolean;
    "vadEnabled": boolean;
    "vadMode": string;
    "vadSensitivity": number;
    "vadOpen": boolean;
}

export interface ChannelDTO {
    "id": string;
    "parentId": string;
    "name": string;
    "topic": string;
    "description": string;
    "position": number;
    "maxUsers": number;
    "audio": AudioProfileDTO;
}

export interface ClientEventDTO {
    "sequence": string;
    "time": string;
    "kind": string;
    "message": string;
    "revision"?: string;
}

export interface ClientViewDTO {
    "connectionStatus": string;
    "lastError"?: string;
    "server": ServerDTO;
    "revision": string;
    "sessionId": string;
    "channelId": string;
    "snapshotFresh": boolean;
    "channels": ChannelDTO[] | null;
    "participants": ParticipantDTO[] | null;
    "audio": AudioStateDTO;
}

export interface ConnectRequest {
    "name": string;
    "server": string;
    "initialChannel": string;
}

export interface ParticipantDTO {
    "sessionId": string;
    "displayName": string;
    "channelId": string;
    "speaking": boolean;
    "local": boolean;
}

export interface ServerDTO {
    "name": string;
}
