// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AudioDevices(): $CancellablePromise<$models.AudioDevicesDTO> {
    return $Call.ByID(689973808);
}

export function Connect(request: $models.ConnectRequest): $CancellablePromise<void> {
    return $Call.ByID(1685769029, request);
}

export function Disconnect(): $CancellablePromise<void> {
    return $Call.ByID(34562471);
}

export function EventsAfter(sequence: string): $CancellablePromise<$models.ClientEventDTO[] | null> {
    return $Call.ByID(952797554, sequence);
}

export function JoinChannel(channelID: string): $CancellablePromise<void> {
    return $Call.ByID(136141940, channelID);
}

export function SetCaptureDevice(id: string): $CancellablePromise<void> {
    return $Call.ByID(691731989, id);
}

export function SetDeafened(value: boolean): $CancellablePromise<void> {
    return $Call.ByID(4111513517, value);
}

export function SetMuted(value: boolean): $CancellablePromise<void> {
    return $Call.ByID(2056801774, value);
}

export function SetPlaybackDevice(id: string): $CancellablePromise<void> {
    return $Call.ByID(2957827556, id);
}

export function SetRNNoiseEnabled(value: boolean): $CancellablePromise<void> {
    return $Call.ByID(1565027940, value);
}

export function SetVADEnabled(value: boolean): $CancellablePromise<void> {
    return $Call.ByID(2506937699, value);
}

export function SetVADMode(value: string): $CancellablePromise<void> {
    return $Call.ByID(4025400381, value);
}

export function SetVADSensitivity(value: number): $CancellablePromise<void> {
    return $Call.ByID(603740493, value);
}

export function Snapshot(): $CancellablePromise<$models.ClientViewDTO> {
    return $Call.ByID(3461296401);
}
