// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as clientapp$0 from "../../clientapp/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as media$0 from "../../media/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

export function AudioDevices(): $CancellablePromise<$models.AudioDevicesDTO> {
    return $Call.ByID(689973808);
}

export function Connect(request: $models.ConnectRequest): $CancellablePromise<void> {
    return $Call.ByID(1685769029, request);
}

export function Disconnect(): $CancellablePromise<void> {
    return $Call.ByID(34562471);
}

export function EventsAfter(sequence: string): $CancellablePromise<$models.ClientEventDTO[] | null> {
    return $Call.ByID(952797554, sequence);
}

export function JoinChannel(channelID: string): $CancellablePromise<void> {
    return $Call.ByID(136141940, channelID);
}

export function MediaServerIdentity(): $CancellablePromise<$models.MediaTrustDTO> {
    return $Call.ByID(891014062);
}

export function OpenScreenWindow(streamID: string, ownerName: string): $CancellablePromise<void> {
    return $Call.ByID(393597545, streamID, ownerName);
}

export function PublishScreen(offer: media$0.SessionDescription): $CancellablePromise<clientapp$0.MediaPublishResult> {
    return $Call.ByID(3026111448, offer);
}

export function SavedDisplayName(): $CancellablePromise<string> {
    return $Call.ByID(1364441037);
}

export function SetCaptureDevice(id: string): $CancellablePromise<void> {
    return $Call.ByID(691731989, id);
}

export function SetDeafened(value: boolean): $CancellablePromise<void> {
    return $Call.ByID(4111513517, value);
}

export function SetMuted(value: boolean): $CancellablePromise<void> {
    return $Call.ByID(2056801774, value);
}

export function SetPlaybackDevice(id: string): $CancellablePromise<void> {
    return $Call.ByID(2957827556, id);
}

export function SetRNNoiseEnabled(value: boolean): $CancellablePromise<void> {
    return $Call.ByID(1565027940, value);
}

export function SetRNNoiseSensitivity(value: number): $CancellablePromise<void> {
    return $Call.ByID(245222922, value);
}

export function SetVADEnabled(value: boolean): $CancellablePromise<void> {
    return $Call.ByID(2506937699, value);
}

export function SetVADMode(value: string): $CancellablePromise<void> {
    return $Call.ByID(4025400381, value);
}

export function SetVADSensitivity(value: number): $CancellablePromise<void> {
    return $Call.ByID(603740493, value);
}

export function Snapshot(): $CancellablePromise<$models.ClientViewDTO> {
    return $Call.ByID(3461296401);
}

export function StopScreen(streamID: string): $CancellablePromise<void> {
    return $Call.ByID(3581875877, streamID);
}

export function SubscribeScreen(streamID: string, subscriberID: string, offer: media$0.SessionDescription): $CancellablePromise<clientapp$0.MediaSubscribeResult> {
    return $Call.ByID(1746283899, streamID, subscriberID, offer);
}

export function TrustMediaServer(fingerprint: string): $CancellablePromise<void> {
    return $Call.ByID(679130948, fingerprint);
}

export function UnsubscribeScreen(streamID: string, subscriberID: string): $CancellablePromise<void> {
    return $Call.ByID(4286357958, streamID, subscriberID);
}
