// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as media$0 from "../media/models.js";

export interface MediaPublishResult {
    "streamId": string;
    "answer": media$0.SessionDescription;
}

export interface MediaSubscribeResult {
    "answer": media$0.SessionDescription;
}
